### ISSUE TITLE
🤖 Create Dedicated Service Account for Automated Workflows

### ISSUE THREAD

**Issue by JamesAlfonse** [WhyDRS/.github#7]
Right now, our automated workflows for the database repository are using my personal email, which means all automated commits show up as if I made them. This makes it hard to distinguish between my manual changes and the automated ones, and it could also pose some security risks. I think we should set up a separate service account for these automated tasks. This way, commits from the automation will be clearly labeled, we can manage permissions more securely, and it will be easier to track and audit automated activities.

**Comment by JFWooten4** [comment]
As far as I've seen with dependabots, this is generally implemented as its own GitHub account&mdash;any username preferences/ideas? 🔩

**Comment by JamesAlfonse** [comment]
No preference here on the name. Maybe Database-bot? Database-commit?

For security reasons it should be assigned admin permissions for just the one repository. Then if other repositories need a service account, they would have segmented permissions as well.

**Comment by JFWooten4** [comment]
Just to keep this documented, we realized that the GitHub webhook recognizes `Actions` from James' account as separate from personal contributions. It also seems we have a [new bot](https://github.com/apps/whydrs-issue-manager) configured 🎉👏

**Comment by JamesAlfonse** [comment]
No service account was needed. Marking this as complete and closing the issue. 

![Screenshot 2024-12-08 at 9 52 13 PM](https://github.com/user-attachments/assets/0bb8dbbf-53ef-4f6a-a5f2-2a61275df67e)

**Comment by JFWooten4** [comment]
I kind of like that it still shows your name @JamesAlfonse directly on GitHub, so we know who's accountable to the activities of the `github-actions[bot]`. One caveat I might like as a new visitor: a comment description in each of the commits. Maybe we could explain what's going on to people following the tree history with something like:

- A description of the bot's actions in like a sentence,
- A (stable) link to the code that defines its behavior, and
- Perhaps a (longstanding) Discussion to mention any mistake?

**Comment by JamesAlfonse** [comment]
@JFWooten4 Fantastic idea. I'm going to make a new issue out of it. Thanks for the input.
